import proverbs from "../../data/kenyan-proverbs.json" with { type: "json" };

function pick<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }

// Dad jokes (hardcoded inline — works reliably)
const DAD_JOKES = [
  "I'm afraid for the calendar. Its days are numbered.",
  "What do you call a fish wearing a bowtie? So-fish-ticated.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "What do you call a fake noodle? An impasta.",
  "I'm reading a book on anti-gravity. It's impossible to put down.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the math book look so sad? It had too many problems.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why did the coffee file a police report? It got mugged.",
  "What's the best thing about Switzerland? The flag is a big plus.",
  "I don't trust stairs. They're always up to something.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why can't a bicycle stand on its own? It's two-tired.",
  "I used to hate facial hair, but then it grew on me.",
  "What did the janitor say when he jumped out of the closet? SUPPLIES!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "I made a pencil with two erasers. It was pointless.",
  "What do you call a pig that does karate? A pork chop.",
  "What do you call a dog that can do magic? A Labracadabrador.",
  "Why did the chicken go to the séance? To talk to the other side.",
  "What does a nosey pepper do? Gets jalapeño business.",
  "I used to be a banker but I lost interest.",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a cow with no legs? Ground beef.",
  "I told a chemistry joke but got no reaction.",
  "Why did the cookie go to the doctor? Because it was feeling crumbly.",
];

const AFFIRMATIONS = [
  "I am capable of achieving greatness today.",
  "My potential is limitless and I embrace new challenges.",
  "I radiate confidence, self-respect, and inner harmony.",
  "Every day I become a better version of myself.",
  "I am worthy of love, success, and happiness.",
  "My mind is full of brilliant ideas.",
  "I attract positive energy and repel negativity.",
  "I am in charge of how I feel and today I choose happiness.",
  "My hard work is paying off and success is coming.",
  "I am grateful for everything I have and excited for everything coming.",
  "I trust the timing of my life.",
  "I am strong, resilient, and can handle anything.",
  "Today I will focus on what I can control.",
  "I am enough — exactly as I am.",
  "My voice matters and my opinions are valuable.",
  "I am building a life I'm proud of.",
  "I choose to see the good in every situation.",
  "I am surrounded by love and support.",
  "My dreams are valid and I'm working toward them daily.",
  "I am not my mistakes. I am my growth.",
  "I am a magnet for miracles and blessings.",
  "Today I release all doubt and step into my power.",
  "I am peace, I am love, I am light.",
  "Money flows to me easily and abundantly.",
  "I am healthy, wealthy, and wise.",
  "My creativity knows no bounds.",
  "I forgive myself and others. I am free.",
  "I am exactly where I need to be right now.",
  "Great things are unfolding in my life.",
  "I embrace change and grow through challenges.",
];

const SWAHILI_PHRASES = [
  { swahili: "Habari yako?", english: "How are you?", category: "Greetings" },
  { swahili: "Nzuri sana", english: "Very good", category: "Greetings" },
  { swahili: "Asante sana", english: "Thank you very much", category: "Common" },
  { swahili: "Tafadhali", english: "Please", category: "Common" },
  { swahili: "Samahani", english: "Sorry / Excuse me", category: "Common" },
  { swahili: "Nakupenda", english: "I love you", category: "Love" },
  { swahili: "Karibu", english: "Welcome", category: "Greetings" },
  { swahili: "Jina langu ni...", english: "My name is...", category: "Introduction" },
  { swahili: "Unatoka wapi?", english: "Where are you from?", category: "Questions" },
  { swahili: "Ninatoka Kenya", english: "I'm from Kenya", category: "Introduction" },
  { swahili: "Lala salama", english: "Sleep well / Goodnight", category: "Greetings" },
  { swahili: "Habari za asubuhi", english: "Good morning", category: "Greetings" },
  { swahili: "Habari za mchana", english: "Good afternoon", category: "Greetings" },
  { swahili: "Habari za jioni", english: "Good evening", category: "Greetings" },
  { swahili: "Kwaheri", english: "Goodbye", category: "Greetings" },
  { swahili: "Tutaonana", english: "See you later", category: "Greetings" },
  { swahili: "Pole pole", english: "Slowly / Take it easy", category: "Common" },
  { swahili: "Hakuna matata", english: "No worries", category: "Common" },
  { swahili: "Sawa sawa", english: "Okay / Alright", category: "Common" },
  { swahili: "Chakula ni kitamu", english: "The food is delicious", category: "Food" },
  { swahili: "Maji tafadhali", english: "Water please", category: "Food" },
  { swahili: "Bei gani?", english: "How much?", category: "Shopping" },
  { swahili: "Ghali sana", english: "Too expensive", category: "Shopping" },
  { swahili: "Nisaidie tafadhali", english: "Help me please", category: "Common" },
  { swahili: "Sielewi", english: "I don't understand", category: "Common" },
  { swahili: "Unasema Kiswahili?", english: "Do you speak Swahili?", category: "Questions" },
  { swahili: "Kidogo", english: "A little", category: "Common" },
  { swahili: "Hongera!", english: "Congratulations!", category: "Common" },
  { swahili: "Safari njema", english: "Safe journey", category: "Common" },
  { swahili: "Mungu akubariki", english: "God bless you", category: "Religious" },
];

export function getKenyanProverb() { return { ...pick(proverbs) }; }
export function getDadJoke() { return { joke: pick(DAD_JOKES) }; }
export function getAffirmation() { return { affirmation: pick(AFFIRMATIONS) }; }
export function getSwahiliPhrase() { return { ...pick(SWAHILI_PHRASES) }; }
export function getAllKenyanProverbs() { return proverbs; }
export function getAllSwahiliPhrases() { return SWAHILI_PHRASES; }
